### ISSUE TITLE
Automatic top face and layout detection

### ISSUE THREAD

**Issue by denizsincar29** [kyo-takano/alphacube#6]
Hello! Lately i'm trying to solve my physical rubic's cube for blind with tactile markings. I was using alphacube. For a Long time couldn't figure out how to enter stickers correctly into the array, but when I did, the cube was failing to solve.
I choosed a random top face, looked to the central pieces of all faces and made sure that the same colors, (or tactile markings since i'm blind), remain the same. I even made a small validator that each color repeats 9 times and there are 6 colors.
However I strongly couldn't get why my cube doesn't solve.
Here's my code:
```python
import numpy as np
import alphacube

# i had incorrect numbers for colors, so i will mark them as letters of tactile marks:
# n: nothing, d: small dot, D: big dot, c: circle, f: flower, b: ladybird

up="cbddDcccc"
down = "bDDnbDfdd"
left = "ffffffcfb"
right = "fbDccDnbd"
back = "DdbDnnnnD"
front = "ddnbdcbnn"

def make_cube(*cube_strings):
    cube = np.zeros(54, dtype=np.int64)
    faces="UDLRBF"
    chartypes="Dbfcnd"
    for i, face in enumerate(faces):
        facestring = cube_strings[i]
        if len(facestring) != 9:
            raise ValueError('Invalid face string: ' + facestring)
        cube[9*i:9*(i+1)] = [chartypes.index(c) for c in facestring]
    # each color must be 9 times
    for i in range(6):
        if np.sum(cube == i) != 9:
            raise ValueError(f'Invalid cube strings, color {i} is not 9 times, but {np.sum(cube == i)}')
    return cube


# create the cube
cube = make_cube(up, down, left, right, back, front)
print("loading model")
alphacube.load()
print("started solving")
result = alphacube.solve(format = "stickers", scramble =     cube, beam_width = 1024)
if result is not None:
    print('Solution:', ' new '.join(result['solutions']))
    print('Length:', len(result['solutions']))
else:
    print('Failed')

```
Any help would be appritiated.

**Comment by denizsincar29** [comment]
Ah yes, I would got the title wrong but here was my feature request. To be able to detect if a rubic's cube is solved even if it's layout and turn was very wrong. It would turn the cube automatically to be in the correct layout of colors.

**Comment by denizsincar29** [comment]
The only way I find is to treet not only the [0]*9 + [1]*9 ... [5]*9 to be a solved state, but also any combinations of numbers that match the pattern (aaaaaaaaa bbbbbbbbb ccccccccc) where A, B and C are the colors of the rubic's cube. Of course all 6 sides must be same color.

**Comment by kyo-takano** [comment]
Hi @denizsincar29,

The case simply cannot be solved because it is not a possible state of the puzzle.
If your code is following the representation scheme as described in [API reference](https://alphacube.dev/docs/api-reference/env), you have the following problems:

- Duplicate RF pieces (circle & small dot) at UF and DR positions
- Illegal UD piece (big dot & ladybird) at DF position
- Absent pieces: UF (big dot & small dot) and RD (circle & ladybird)

You would need to either fix the representation or disassemble the physical cube to solve.

With regards to your request, `alphacube` already does so by reading the colors of given center stickers.

https://github.com/kyo-takano/alphacube/blob/1155d9696cf7bcfd72e993003cdbb4a622916a4f/alphacube/core.py#L102

**Comment by denizsincar29** [comment]
Thank you so much, i'll maybe consider to rethink | rewrite the faces with a cited person. But I think I got the central piece thaught right that the central pieces must match the colors.
